/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Compra;
import ar.com.gmeventas.entities.Producto;
import ar.com.gmeventas.entities.ProductoTop;
import ar.com.gmeventas.services.CompraService;
import ar.com.gmeventas.services.ProductoService;
import ar.com.gmeventas.services.ProductoTopService;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class NuevoStockFrame extends javax.swing.JFrame {

    private List<Producto> productos = null;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form NuevoStockFrame
     */
    public NuevoStockFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 100, 255));
        this.setLocationRelativeTo(null);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filtroTxt = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        proveedorTxt = new javax.swing.JTextField();
        comprobanteTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        nuevoBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        precioTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        impuestoTxt = new javax.swing.JTextField();
        actualizarChk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO STOCK");

        jLabel1.setText("Proveedor:");

        jLabel2.setText("Comprobante:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Buscar Producto:");

        filtroTxt.setText("FILTRO");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        proveedorTxt.setText("PROVEEDOR");

        comprobanteTxt.setText("COMPROBANTE");

        fechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaTxt.setText("FECHA");

        jLabel5.setText("Cantidad:");

        cantidadTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadTxt.setText("CANTIDAD");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Nuevo Precio:");

        precioTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioTxt.setText("PRECIO");

        jLabel7.setText("Nuevo Impuesto:");

        impuestoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoTxt.setText("IMPUESTO");

        actualizarChk.setText("Actualizar Precio");
        actualizarChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(buscarBtn))
                                        .addComponent(proveedorTxt)
                                        .addComponent(comprobanteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(precioTxt))
                                .addGap(79, 79, 79)
                                .addComponent(actualizarChk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(proveedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comprobanteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarChk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(nuevoBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        nuevo();
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        buscar();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void actualizarChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarChkActionPerformed
        if (actualizarChk.isSelected()) {
            precioTxt.setEditable(true);
            impuestoTxt.setEditable(true);
        } else {
            precioTxt.setEditable(false);
            impuestoTxt.setEditable(false);
        }
    }//GEN-LAST:event_actualizarChkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoStockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox actualizarChk;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField comprobanteTxt;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField impuestoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JTextField proveedorTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if (validar()) {
            Compra co = new Compra();
            co.setProveedor(proveedorTxt.getText());
            co.setComprobante(comprobanteTxt.getText());
            try {
                co.setFecha(sdf.parse(fechaTxt.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(NuevoStockFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            int ro = combo.getSelectedIndex();
            Producto producto = productos.get(ro - 1);
            if (co.getCantidad() != null) {
                Float cani = co.getCantidad();
                co.setCantidad(cani + Float.valueOf(cantidadTxt.getText().replace(",", ".")));
            }else{
                co.setCantidad(Float.valueOf(cantidadTxt.getText().replace(",", ".")));
            }
            if (actualizarChk.isSelected()) {
                co.setNuevoPrecio(Double.valueOf(precioTxt.getText().replace(",", ".")));
                co.setNuevoImpuesto(Float.valueOf(impuestoTxt.getText().replace(",", ".")));
                producto.setPrecio(co.getNuevoPrecio());
                producto.setImpuesto(co.getNuevoImpuesto());
                if (producto.getStock() != null) {
                    producto.setStock(producto.getStock() + co.getCantidad());
                } else {
                    producto.setStock(co.getCantidad());
                }
            } else {
                Double dl = 0.0;
                Float fl = 0F;
                co.setNuevoPrecio(Double.valueOf(dl));
                co.setNuevoImpuesto(Float.valueOf(fl));
                if (producto.getStock() != null) {
                    producto.setStock(producto.getStock() + co.getCantidad());
                } else {
                    producto.setStock(co.getCantidad());
                }
            }
            Integer cod = producto.getCodigo();
            ProductoTop pt = null;
            try {
                pt = new ProductoTopService().getProductoTopByCodigo(cod);
            } catch (Exception ex) {
//                Logger.getLogger(NuevoStockFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(pt != null){
                pt.setStock(producto.getStock());
            }
////            System.out.println(producto);
////            System.out.println(co);
//            JOptionPane.showMessageDialog(this, ro);
            try {
                producto = new ProductoService().updateProducto(producto);
                co.setProducto(producto);
                new CompraService().saveCompra(co);
                if(pt != null){
                    new ProductoTopService().updateProductoTop(pt);
                }
                limpiarAbajo();
            } catch (Exception ex) {
                Logger.getLogger(NuevoStockFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void nuevo() {
        limpiarCampos();
    }

    private void volver() {
        AbmStockFrame asf = new AbmStockFrame();
        asf.setVisible(true);
        this.dispose();
    }

    private void limpiarCampos() {
        proveedorTxt.setText("");
        comprobanteTxt.setText("");
        fechaTxt.setText("");
        combo.removeAllItems();
        filtroTxt.setText("");
        cantidadTxt.setText("");
        actualizarChk.setSelected(false);
        precioTxt.setText("");
        impuestoTxt.setText("");
        precioTxt.setEditable(false);
        impuestoTxt.setEditable(false);
    }

    private void llenarCombo() {
        combo.removeAllItems();
        combo.addItem("");
        String filtro = filtroTxt.getText();
        productos = null;
        try {
            productos = new ProductoService().getAllProductosOrdenadoByNombre(filtro);
        } catch (Exception ex) {
            Logger.getLogger(NuevoStockFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (productos != null && !productos.isEmpty()) {
            for (Producto p : productos) {
                combo.addItem(p.getDetalle());
            }
        }
    }

    private void buscar() {
        if (!filtroTxt.getText().isEmpty()) {
            llenarCombo();
        }
    }

    private boolean validar() {
        if (proveedorTxt.getText().isEmpty()) {
            proveedorTxt.requestFocus();
            return false;
        }
        if (comprobanteTxt.getText().isEmpty()) {
            comprobanteTxt.requestFocus();
            return false;
        }
        if (fechaTxt.getText().isEmpty()) {
            fechaTxt.requestFocus();
            return false;
        }
        int lar = fechaTxt.getText().length();
        if (lar != 10) {
            fechaTxt.requestFocus();
            JOptionPane.showMessageDialog(this, "LA FECHA DEBE INGRESARSE COMPLETA xx/xx/xxxx");
            return false;
        }
        int r = combo.getSelectedIndex();
        if (r < 1) {
            combo.requestFocus();
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN PRODUCTO");
            return false;
        }
        if (!cantidadTxt.getText().isEmpty()) {
            Float cantidad = Float.valueOf(cantidadTxt.getText());
            if (cantidad < 1) {
                cantidadTxt.requestFocus();
                return false;
            }
        } else {
            cantidadTxt.requestFocus();
            return false;
        }
        if (actualizarChk.isSelected()) {
            if (precioTxt.getText().isEmpty()) {
                precioTxt.requestFocus();
                return false;
            }
            if (impuestoTxt.getText().isEmpty()) {
                impuestoTxt.requestFocus();
                return false;
            }
        }
        return true;
    }

    private void limpiarAbajo() {
        filtroTxt.setText("");
        combo.removeAllItems();
        cantidadTxt.setText("");
        precioTxt.setText("");
        impuestoTxt.setText("");
        actualizarChk.setSelected(false);
        filtroTxt.requestFocus();
    }
}
